version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli typescript
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - amplifyPush --simple
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/wealth-tracker
